theme: jekyll-theme-cayman
title: Test Title
description: The Classroom VR Open Standards (CVROS) are a set of open-source guidelines for how to best deploy virtual reality technology in classroom settings.
